In [20]:
import pytesseract
pytesseract.pytesseract.tesseract_cmd = r'C:\\Program Files\\Tesseract-OCR\\tesseract.exe'

In [21]:
import cv2

In [28]:
img=cv2.imread(r'C:\Users\suzan\Desktop\PANDA\1.jpg')
cv2.imshow('sample image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

TypeError: Argument 'flags' is required to be an integer

In [23]:
text=pytesseract.image_to_data(img)
print(img)

[[[  4   7  11]
  [  4   7  11]
  [  4   7  12]
  ...
  [  2   5  10]
  [  0   1   6]
  [  4   7  12]]

 [[  4   7  11]
  [  4   7  11]
  [  4   7  12]
  ...
  [  9  12  17]
  [ 10  13  18]
  [ 10  13  18]]

 [[  4   7  12]
  [  4   7  12]
  [  4   7  12]
  ...
  [ 12  15  20]
  [ 15  18  23]
  [ 14  17  22]]

 ...

 [[104 110 115]
  [104 110 115]
  [105 111 116]
  ...
  [ 87  91  96]
  [ 87  91  96]
  [ 85  87  95]]

 [[100 106 111]
  [101 107 112]
  [103 109 114]
  ...
  [ 86  90  95]
  [ 86  90  95]
  [ 84  86  94]]

 [[ 96 102 107]
  [ 98 104 109]
  [101 107 112]
  ...
  [ 86  90  95]
  [ 86  90  95]
  [ 85  84  93]]]


In [24]:
img.shape

(1600, 1201, 3)

In [1]:
import numpy as np
import pandas as pd
#img.to_csv('sample1.csv')

In [8]:
#print(pytesseract.get_languages(config=''))
print(pytesseract.get_languages())

['eng', 'osd']


In [26]:
output = pytesseract.image_to_data(img)
with open('test.csv','w') as f: 
    f.write(output) 